"""empty message

Revision ID: 29a8ae1aa65a
Revises: 0ebebaa54e1e
Create Date: 2019-07-01 17:39:43.330125

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '29a8ae1aa65a'
revision = "29a8ae1aa65a"
down_revision = "0ebebaa54e1e"
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technology_frameworks')
    op.drop_table("technology_frameworks")
    op.add_column("framework", sa.Column("technology_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "framework", "technology", ["technology_id"], ["id"])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'framework', type_='foreignkey')
    op.drop_constraint(None, "framework", type_="foreignkey")
    op.drop_column("framework", "technology_id")
    op.create_table(
        "technology_frameworks",
        sa.Column("framework_id", sa.INTEGER(), nullable=False),
        sa.Column("technology_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["framework_id"], ["framework.id"]),
        sa.ForeignKeyConstraint(["technology_id"], ["technology.id"]),
        sa.PrimaryKeyConstraint("framework_id", "technology_id"),
    # ### end Alembic commands ###
